name: ejer12_galeria_img
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/post0.jpg
    - lib/assets/post1.jpg
    - lib/assets/post2.jpg
    - lib/assets/post3.jpg
    - lib/assets/post4.jpg
    - lib/assets/post5.jpg
    - lib/assets/post6.jpg
    - lib/assets/post7.jpg
    - lib/assets/post8.jpg
    - lib/assets/post9.jpg
